DROP TABLE IF EXISTS beverages CASCADE;
CREATE TABLE beverages (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  thumbnail_url VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  posted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  sold_at TIMESTAMP,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);
